#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

caesar: caesar.c
#	gcc -ggdb -std=c99 -Wall -Werror -o caesar caesar.c -lcs50
	gcc -ggdb -std=c99 -Wall -o caesar caesar.c -lcs50

vigenere: vigenere.c
	gcc -ggdb -std=c99 -Wall -o vigenere vigenere.c -lcs50

clean:
	rm -f *.o a.out core caesar
	rm -f *.o a.out core vigenere
