#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

fifteen: myfifteen.c
	#gcc -ggdb -std=c99 -Wall -Werror -o fifteen myfifteen.c -lcs50
	gcc -ggdb -std=c99 -Wall -o fifteen myfifteen.c -lcs50

clean:
	rm -f *.o a.out core fifteen
